# Generated by Django 4.2.5 on 2023-09-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0002_csvforheatmaptest_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvforheatmaptest',
            name='Line',
            field=models.CharField(max_length=255),
        ),
    ]
