# Generated by Django 4.2.5 on 2023-09-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0007_vi_csv_no51_machun'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vi_CSV_NO51_Machun',
            new_name='Vi_CSV_NO51',
        ),
    ]
