# Generated by Django 4.2.5 on 2023-09-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_selection_result_alter_testcsv_subway_sw_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcsv_subway',
            name='SW_Station',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
