# Generated by Django 4.2.5 on 2023-09-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0003_alter_testcsv_subway_sw_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALL_LN_HS_F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SW_ID', models.IntegerField()),
                ('LINE', models.IntegerField()),
                ('STATION', models.CharField(max_length=100)),
            ],
        ),
    ]
