# Generated by Django 4.2.5 on 2023-09-19 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0004_all_ln_hs_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_ln_hs_f',
            name='LINE',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
