# Generated by Django 4.2.5 on 2023-09-19 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0005_alter_all_ln_hs_f_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_ln_hs_f',
            name='STATION',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='all_ln_hs_f',
            name='SW_ID',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
