# Generated by Django 4.2.5 on 2023-09-20 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0006_alter_all_ln_hs_f_station_alter_all_ln_hs_f_sw_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_ln_hs_f',
            name='LINE',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
