from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


# Create your models here.

class CSVForHeatmapTest(models.Model):
    Station = models.CharField(max_length=255)
    Line = models.CharField(max_length=255)
    Time_06 = models.FloatField()
    Time_07 = models.FloatField()
    Time_08 = models.FloatField()
    Time_09 = models.FloatField()
    Time_10 = models.FloatField()
    Time_11 = models.FloatField()
    Time_12 = models.FloatField()
    Time_13 = models.FloatField()
    Time_14 = models.FloatField()
    Time_15 = models.FloatField()
    Time_16 = models.FloatField()
    Time_17 = models.FloatField()
    Time_18 = models.FloatField()
    Time_19 = models.FloatField()
    Time_20 = models.FloatField()
    Time_21 = models.FloatField()
    Time_22 = models.FloatField()
    Time_23 = models.FloatField()


class Vi_CSV_NO1(models.Model):
    MONTH = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])
    DAY = models.CharField(max_length=255)
    STATION = models.CharField(max_length=255)
    DIRECTION = models.CharField(max_length=255)
    TIME_05 = models.FloatField()
    TIME_06 = models.FloatField()
    TIME_07 = models.FloatField()
    TIME_08 = models.FloatField()
    TIME_09 = models.FloatField()
    TIME_10 = models.FloatField()
    TIME_11 = models.FloatField()
    TIME_12 = models.FloatField()
    TIME_13 = models.FloatField()
    TIME_14 = models.FloatField()
    TIME_15 = models.FloatField()
    TIME_16 = models.FloatField()
    TIME_17 = models.FloatField()
    TIME_18 = models.FloatField()
    TIME_19 = models.FloatField()
    TIME_20 = models.FloatField()
    TIME_21 = models.FloatField()
    TIME_22 = models.FloatField()
    TIME_23 = models.FloatField()
    TIME_24 = models.FloatField()

class Vi_CSV_NO2(models.Model):
    MONTH = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])
    DAY = models.CharField(max_length=255)
    STATION = models.CharField(max_length=255)
    DIRECTION = models.CharField(max_length=255)
    TIME_05 = models.FloatField()
    TIME_06 = models.FloatField()
    TIME_07 = models.FloatField()
    TIME_08 = models.FloatField()
    TIME_09 = models.FloatField()
    TIME_10 = models.FloatField()
    TIME_11 = models.FloatField()
    TIME_12 = models.FloatField()
    TIME_13 = models.FloatField()
    TIME_14 = models.FloatField()
    TIME_15 = models.FloatField()
    TIME_16 = models.FloatField()
    TIME_17 = models.FloatField()
    TIME_18 = models.FloatField()
    TIME_19 = models.FloatField()
    TIME_20 = models.FloatField()
    TIME_21 = models.FloatField()
    TIME_22 = models.FloatField()
    TIME_23 = models.FloatField()
    TIME_24 = models.FloatField()

class Vi_CSV_NO3(models.Model):
    MONTH = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])
    DAY = models.CharField(max_length=255)
    STATION = models.CharField(max_length=255)
    DIRECTION = models.CharField(max_length=255)
    TIME_05 = models.FloatField()
    TIME_06 = models.FloatField()
    TIME_07 = models.FloatField()
    TIME_08 = models.FloatField()
    TIME_09 = models.FloatField()
    TIME_10 = models.FloatField()
    TIME_11 = models.FloatField()
    TIME_12 = models.FloatField()
    TIME_13 = models.FloatField()
    TIME_14 = models.FloatField()
    TIME_15 = models.FloatField()
    TIME_16 = models.FloatField()
    TIME_17 = models.FloatField()
    TIME_18 = models.FloatField()
    TIME_19 = models.FloatField()
    TIME_20 = models.FloatField()
    TIME_21 = models.FloatField()
    TIME_22 = models.FloatField()
    TIME_23 = models.FloatField()
    TIME_24 = models.FloatField()

class Vi_CSV_NO4(models.Model):
    MONTH = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])
    DAY = models.CharField(max_length=255)
    STATION = models.CharField(max_length=255)
    DIRECTION = models.CharField(max_length=255)
    TIME_05 = models.FloatField()
    TIME_06 = models.FloatField()
    TIME_07 = models.FloatField()
    TIME_08 = models.FloatField()
    TIME_09 = models.FloatField()
    TIME_10 = models.FloatField()
    TIME_11 = models.FloatField()
    TIME_12 = models.FloatField()
    TIME_13 = models.FloatField()
    TIME_14 = models.FloatField()
    TIME_15 = models.FloatField()
    TIME_16 = models.FloatField()
    TIME_17 = models.FloatField()
    TIME_18 = models.FloatField()
    TIME_19 = models.FloatField()
    TIME_20 = models.FloatField()
    TIME_21 = models.FloatField()
    TIME_22 = models.FloatField()
    TIME_23 = models.FloatField()
    TIME_24 = models.FloatField()

class Vi_CSV_NO5(models.Model):
    MONTH = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])
    DAY = models.CharField(max_length=255)
    STATION = models.CharField(max_length=255)
    DIRECTION = models.CharField(max_length=255)
    TIME_05 = models.FloatField()
    TIME_06 = models.FloatField()
    TIME_07 = models.FloatField()
    TIME_08 = models.FloatField()
    TIME_09 = models.FloatField()
    TIME_10 = models.FloatField()
    TIME_11 = models.FloatField()
    TIME_12 = models.FloatField()
    TIME_13 = models.FloatField()
    TIME_14 = models.FloatField()
    TIME_15 = models.FloatField()
    TIME_16 = models.FloatField()
    TIME_17 = models.FloatField()
    TIME_18 = models.FloatField()
    TIME_19 = models.FloatField()
    TIME_20 = models.FloatField()
    TIME_21 = models.FloatField()
    TIME_22 = models.FloatField()
    TIME_23 = models.FloatField()
    TIME_24 = models.FloatField()

class Vi_CSV_NO51(models.Model):
    MONTH = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])
    DAY = models.CharField(max_length=255)
    STATION = models.CharField(max_length=255)
    DIRECTION = models.CharField(max_length=255)
    TIME_05 = models.FloatField()
    TIME_06 = models.FloatField()
    TIME_07 = models.FloatField()
    TIME_08 = models.FloatField()
    TIME_09 = models.FloatField()
    TIME_10 = models.FloatField()
    TIME_11 = models.FloatField()
    TIME_12 = models.FloatField()
    TIME_13 = models.FloatField()
    TIME_14 = models.FloatField()
    TIME_15 = models.FloatField()
    TIME_16 = models.FloatField()
    TIME_17 = models.FloatField()
    TIME_18 = models.FloatField()
    TIME_19 = models.FloatField()
    TIME_20 = models.FloatField()
    TIME_21 = models.FloatField()
    TIME_22 = models.FloatField()
    TIME_23 = models.FloatField()
    TIME_24 = models.FloatField()

class Vi_CSV_NO6(models.Model):
    MONTH = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])
    DAY = models.CharField(max_length=255)
    STATION = models.CharField(max_length=255)
    DIRECTION = models.CharField(max_length=255)
    TIME_05 = models.FloatField()
    TIME_06 = models.FloatField()
    TIME_07 = models.FloatField()
    TIME_08 = models.FloatField()
    TIME_09 = models.FloatField()
    TIME_10 = models.FloatField()
    TIME_11 = models.FloatField()
    TIME_12 = models.FloatField()
    TIME_13 = models.FloatField()
    TIME_14 = models.FloatField()
    TIME_15 = models.FloatField()
    TIME_16 = models.FloatField()
    TIME_17 = models.FloatField()
    TIME_18 = models.FloatField()
    TIME_19 = models.FloatField()
    TIME_20 = models.FloatField()
    TIME_21 = models.FloatField()
    TIME_22 = models.FloatField()
    TIME_23 = models.FloatField()
    TIME_24 = models.FloatField()

class Vi_CSV_NO7(models.Model):
    MONTH = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])
    DAY = models.CharField(max_length=255)
    STATION = models.CharField(max_length=255)
    DIRECTION = models.CharField(max_length=255)
    TIME_05 = models.FloatField()
    TIME_06 = models.FloatField()
    TIME_07 = models.FloatField()
    TIME_08 = models.FloatField()
    TIME_09 = models.FloatField()
    TIME_10 = models.FloatField()
    TIME_11 = models.FloatField()
    TIME_12 = models.FloatField()
    TIME_13 = models.FloatField()
    TIME_14 = models.FloatField()
    TIME_15 = models.FloatField()
    TIME_16 = models.FloatField()
    TIME_17 = models.FloatField()
    TIME_18 = models.FloatField()
    TIME_19 = models.FloatField()
    TIME_20 = models.FloatField()
    TIME_21 = models.FloatField()
    TIME_22 = models.FloatField()
    TIME_23 = models.FloatField()
    TIME_24 = models.FloatField()

class Vi_CSV_NO8(models.Model):
    MONTH = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(12)])
    DAY = models.CharField(max_length=255)
    STATION = models.CharField(max_length=255)
    DIRECTION = models.CharField(max_length=255)
    TIME_05 = models.FloatField()
    TIME_06 = models.FloatField()
    TIME_07 = models.FloatField()
    TIME_08 = models.FloatField()
    TIME_09 = models.FloatField()
    TIME_10 = models.FloatField()
    TIME_11 = models.FloatField()
    TIME_12 = models.FloatField()
    TIME_13 = models.FloatField()
    TIME_14 = models.FloatField()
    TIME_15 = models.FloatField()
    TIME_16 = models.FloatField()
    TIME_17 = models.FloatField()
    TIME_18 = models.FloatField()
    TIME_19 = models.FloatField()
    TIME_20 = models.FloatField()
    TIME_21 = models.FloatField()
    TIME_22 = models.FloatField()
    TIME_23 = models.FloatField()
    TIME_24 = models.FloatField()
